### ISSUE TITLE
Error for float single plane

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-vsTCanny#1]
I get an error in the form:
`Filter error: GetPlaneWidthSubsampling not available on greyscale pixel type.`
I managed to trigger it with the next call
```
ExtractY()
ConvertBits(32, fulls=false, fulld=true)
vsTCanny(sigmay=4, sigma_vY=4, mode=-1)
```

**Comment by Asd-g** [comment]
You can try the latest version.

**Comment by Dogway** [comment]
Thanks!
