### ISSUE TITLE
No chroma vertical blurring

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-vsTCanny#3]
Sorry to bother again. Is this correct?
```
vsTCanny(sigmaY=5,sigmaU=5,mode=-1,y=3,u=3,v=3)
ExtractU()
```
I though sigma_vU was inherited from sigmaU. (And sigmaV from sigmaU which works properly)

**Comment by Asd-g** [comment]
sigma_vU is inherited from sigma_vY which is inherited from sigmaY. In your example sigma_vU=2.5 for subsampled chroma.

I guess it's more intuitive if sigma_vU/sigma_vV is inherited from sigma_U/sigma_V?

**Comment by Dogway** [comment]
For simplicity I tend in filters to use:
`vsTCanny(5,2.5,mode=-1,y=3,u=3,v=3) # I read as 5 Luma 2.5 Chroma`
or
`vsTCanny(5,2.5,2.5,mode=-1,y=3,u=3,v=3) # I read as 5 Luma 2.5 U 2.5 V`

In these situations chroma is only burred horizontally, for vertical chroma I would need to be very verbose:
`vsTCanny(5,2.5,2.5,5,2.5,2.5,mode=-1,y=3,u=3,v=3)`

Assymetrical blurring is rarely used so syntax wise I prefer plane syntax as is the current order of the args.

I just noticed vsTCanny is now chroma subsampling aware, so for example for the above calls (given I want to correlate blurring for chroma in a YUV420).
`vsTCanny(5,mode=-1,y=3,u=3,v=3)`
seems enough.

**Comment by Asd-g** [comment]
Yes, all above examples are identical.

Fixed default values of sigmaU/V and sigma_vU/vV for RGB in the latest version.
Vertical sigma is inherited from the horizontal one. They will be equal for chroma subsampling formats different than 422/411. From README.md
```
Default:
- sigma_vY = sigmaY
- sigma_vU = sigmaU if horizontal_chroma_subsampling_factor_and_vertical_chroma_subsampling_factor_equal else sigmaU * horizontal_chroma_subsampling_factor
- sigma_vV = sigma_vU
```

**Comment by Dogway** [comment]
Thank you! it seems to work but for asymmetrical now looks a bit confusing.
It requires:
`vsTCanny(5,sigma_vY=4,sigma_vU=2,mode=-1,y=3,u=3,v=3)`

Would this make more sense?:
```
Default:
- sigma_vY = sigmaY
- sigma_vU = sigma_vY / vertical_chroma_subsampling_factor
- sigma_vV = sigma_vU
```

So arguments work as in cascade, honoring each preceding one.

`vsTCanny(5,sigma_vY=4,mode=-1,y=3,u=3,v=3)`

**Comment by Asd-g** [comment]
Your suggestion is what the previous defaults are (< 1.1.6) - `Default: sigma_vY = sigmaY; sigma_vU = sigma_vV = sigma_vY/2 for half resolution chroma and sigma_vU = sigma_vV = sigma_vY for full resolution chroma.` (https://github.com/Asd-g/AviSynth-vsTCanny/blob/fabe7f34bc7cd6b466b2960d86e95f513bb845d1/README.md) (sigma_vV = sigma_vU).

Actually I suppose a mix would be perfect:
```
- sigma_vY = sigmaY
- if sigmaY == sigma_vY: sigma_vU = sigmaU if horizontal_chroma_subsampling_factor and vertical_chroma_subsampling_factor are equal else sigma_vU = sigmaU * horizontal_chroma_subsampling_factor
- if sigmaY != sigma_vY: sigma_vU = sigma_vY / vertical_chroma_subsampling_factor
- sigma_vV = sigma_vU
```

**Comment by Dogway** [comment]
Yes, a mixed behaviour might be better, expanding on your take, sigma_vU reads from sigmaU only when sigma_vY is not defined:

Assumes YUV420 input

Luma+Chroma (symmetrical)
`vsTCanny(5,3,mode=-1,y=3,u=3,v=3)`

Luma+Chroma (asymmetrical)
`vsTCanny(5,sigma_vY=3,mode=-1,y=3,u=3,v=3)`

Luma (symmetrical) | Chroma (asymmetrical -sigma_vU to counteract sigmaU, or also to use an asymmetrical vertical chroma-)
`vsTCanny(5,1,sigma_vU=2.5,mode=-1,y=3,u=3,v=3)`
or in this case (sigma_vU is half chroma for YV12) sigma_vU can read from sigma_vY
`vsTCanny(5,1,sigma_vY=5,mode=-1,y=3,u=3,v=3)`

Luma (asymmetrical) | Chroma (symmetrical -sigma_vU to counteract sigma_vY-)
`vsTCanny(5,sigma_vY=2,sigma_vU=2.5,mode=-1,y=3,u=3,v=3)`
for another sigma in chroma:
`vsTCanny(5,3,sigma_vY=2,sigma_vU=3,mode=-1,y=3,u=3,v=3)`

Luma (asymmetrical) | Chroma (asymmetrical)
`vsTCanny(5,1,sigma_vY=2,sigma_vU=0,mode=-1,y=3,u=3,v=3)`

So the more unusual gets more verbose, if this makes sense to you.

**Comment by Asd-g** [comment]
Can you try this version - [vsTCanny.zip](https://github.com/Asd-g/AviSynth-vsTCanny/files/8212388/vsTCanny.zip) ?
 
Now sigma is:
```
- sigma_vY = sigmaY
- if sigma_vY not defined: sigma_vU = sigmaU if horizontal and vertical subsampling factors are equal else sigma_vU = sigmaU * horizontal_chroma_subsampling_factor
- if sigma_vY defined: sigma_vU = sigma_vY / vertical_chroma_subsampling_factor
- sigma_vV = sigma_vU
```

**Comment by Dogway** [comment]
Tested thoroughly, works great now, thank you!
