### ISSUE TITLE
Issue on single plane?

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-vsTCanny#4]
I get the following error when trying to filter a single plane clip with v1.1.7:

```
ExtractY()
vsTCanny(sigmaY=1, mode=-1)
```
`vsTCanny: sigma_vY must be greater than or equal to 0.0.`

**Comment by Asd-g** [comment]
Please try 1.1.8.

**Comment by Dogway** [comment]
Thanks! Working great now

**Comment by Asd-g** [comment]
Btw the latest version is faster > 15% compared to 1.1.7 when testing:
```
ExtractY()
vsTCanny(sigmaY=1, sigma_vY=1, mode=-1, opt=2)
```
